# Generated by Django 6.0.5 on 2026-08-23 19:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('poster_url', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('imdb_rating', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('release_date', models.DateField()),
                ('country', models.ManyToManyField(to='catalog.country')),
                ('genre', models.ManyToManyField(to='catalog.genre')),
                ('language', models.ManyToManyField(to='catalog.language')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('actor', 'Actor'), ('director', 'Director'), ('writer', 'Writer')], max_length=100)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.person')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='people',
            field=models.ManyToManyField(through='content.Role', through_fields=('movie', 'person'), to='people.person'),
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.IntegerField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.season')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('poster_url', models.URLField()),
                ('description', models.TextField()),
                ('imdb_rating', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('duration', models.PositiveIntegerField()),
                ('release_date', models.DateField()),
                ('country', models.ManyToManyField(to='catalog.country')),
                ('genre', models.ManyToManyField(to='catalog.genre')),
                ('language', models.ManyToManyField(to='catalog.language')),
                ('people', models.ManyToManyField(through='content.Role', through_fields=('series', 'person'), to='people.person')),
            ],
        ),
        migrations.AddField(
            model_name='season',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.series'),
        ),
        migrations.AddField(
            model_name='role',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.series'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.series')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.movie')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.series')),
            ],
        ),
        migrations.CreateModel(
            name='StreamEpisodeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoder', models.CharField(max_length=100)),
                ('size_mb', models.PositiveIntegerField()),
                ('sub_chose', models.CharField(choices=[('original', 'Original'), ('subtitle', 'Subtitle'), ('dubbed', 'Dubbed')], max_length=100)),
                ('sub_file', models.FileField(upload_to='')),
                ('url', models.URLField()),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.episode')),
                ('quality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.quality')),
            ],
        ),
        migrations.CreateModel(
            name='StreamMovieLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoder', models.CharField(max_length=100)),
                ('size_mb', models.PositiveIntegerField()),
                ('sub_chose', models.CharField(choices=[('original', 'Original'), ('subtitle', 'Subtitle'), ('dubbed', 'Dubbed')], max_length=100)),
                ('sub_file', models.FileField(upload_to='')),
                ('url', models.URLField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.movie')),
                ('quality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.quality')),
            ],
        ),
        migrations.AddConstraint(
            model_name='episode',
            constraint=models.UniqueConstraint(fields=('season', 'episode_number'), name='unique_season_episode_number'),
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.UniqueConstraint(fields=('series', 'season_number'), name='unique_series_season_number'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('person', 'movie', 'series', 'role_type'), name='unique_person_content_role'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('user', 'movie', 'series'), name='unique_user_content_rating'),
        ),
    ]
