# Generated by Django 6.0.5 on 2026-08-29 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rating',
            name='unique_user_content_rating',
        ),
        migrations.AlterField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_season', to='content.season'),
        ),
        migrations.AlterField(
            model_name='season',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_link', to='content.series'),
        ),
        migrations.AlterField(
            model_name='streamepisodelink',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_link', to='content.episode'),
        ),
        migrations.AlterField(
            model_name='streamepisodelink',
            name='sub_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='streammovielink',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_link', to='content.movie'),
        ),
        migrations.AlterField(
            model_name='streammovielink',
            name='sub_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(condition=models.Q(('movie__isnull', False)), fields=('user', 'movie'), name='unique_user_content_rating'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(condition=models.Q(('series__isnull', False)), fields=('user', 'series'), name='unique_series_content_rating'),
        ),
    ]
