# Generated by Django 6.0.5 on 2026-08-29 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_rating_unique_user_content_rating_and_more'),
        ('special', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='recentlywatched',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recently_watched', to='content.movie'),
        ),
        migrations.AlterField(
            model_name='recentlywatched',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recently_watched', to='content.series'),
        ),
        migrations.CreateModel(
            name='FolderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='special.folder')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.movie')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.series')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('movie__isnull', False)), fields=('folder', 'movie'), name='unique_item_folder'), models.UniqueConstraint(condition=models.Q(('series__isnull', False)), fields=('folder', 'series'), name='unique_series_content_folder')],
            },
        ),
    ]
