# Generated by Django 6.0.5 on 2026-08-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_url', models.URLField()),
                ('full_name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
            ],
        ),
    ]
